# Generated by Django 2.1.7 on 2019-03-11 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('modifications_timestamp', models.DateTimeField(auto_now=True, verbose_name='modification time')),
                ('message_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='comment_author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('modifications_timestamp', models.DateTimeField(auto_now=True, verbose_name='modification time')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=30)),
                ('descriptions', models.TextField(max_length=2000)),
                ('project_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managers', to=settings.AUTH_USER_MODEL, verbose_name='project manager')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('modifications_timestamp', models.DateTimeField(auto_now=True, verbose_name='modification time')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=30)),
                ('descriptions', models.TextField(max_length=2000)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'status',
                'verbose_name_plural': 'statuses',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('modifications_timestamp', models.DateTimeField(auto_now=True, verbose_name='modification time')),
                ('slug', models.SlugField(max_length=30)),
                ('descriptions', models.TextField(max_length=2000)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('task_result_url', models.URLField()),
                ('task_price', models.FloatField()),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='projects.Task')),
                ('task_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.Project', verbose_name='project')),
                ('task_staff', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='task staff')),
                ('task_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Status', verbose_name='task status')),
            ],
            options={
                'verbose_name': 'task',
                'verbose_name_plural': 'tasks',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.ForeignKey(on_delete=models.SET('undefined'), to='projects.Status', verbose_name='project status'),
        ),
        migrations.AddField(
            model_name='message',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='projects.Task'),
        ),
    ]
